name: pnf
description: Portable Network File.
version: 1.3.3
homepage: https://github.com/dimpart/demo-dart
repository: https://github.com/dimpart/demo-dart
issue_tracker: https://github.com/dimpart/demo-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
   path: ^1.8.0
   dio: ^5.3.3
   pointycastle: ^3.7.2
   object_key: ^1.1.1
   startrek: ^1.1.2
   mkm: ^2.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
